server:
  port: 8080

spring:
  application:
    name: band
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

bands:
  api:
    url: ${BAND_REMOTE_SERVICE_URL}
    connection-timeout: 5000
    read-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    health:
      show-details: always
